language: go

go:
  - 1.4
  - tip

env:
  - GOARCH=amd64

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=configuration.coverprofile ./configuration
  - go test -coverprofile=api.coverprofile ./api
  - go test -coverprofile=utils.coverprofile ./utils
  - go test -coverprofile=utils.coverprofile ./data
  - go test -coverprofile=main.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci

notifications:
  email:
    on_success: change
    on_failure: always